driebit/ginger

- Makefile
Enables foo.ginger.dev in the Driebit office lan. Since it is not dependent on the ginger containers running (and the ginger container isn't dependent on it), I figured it would be best to make it a separate command, to be run on-demand, which starts a container in daemon mode.
> Add 'make disco' command to enable discovery

- modules/mod_ginger_foundation/templates/_script.tpl
Saves page loading time when google maps is not needed on a site and prevents javascript errors when no api key is configured
> Exclude googlemaps javascript loading when mod_geo is not configured

- modules/mod_ginger_rdf/models/m_rdf.erl
- modules/mod_ginger_rdf/templates/_html_head.tpl
- modules/mod_ginger_rdf/templates/_script.tpl
- modules/mod_ginger_rdf/templates/rdf/resource.tpl
Fix #179.
* Add an alternate link.
* Because search engines don't follow those links, also include the JSON-LD in the page.
* Tested against Google's structured data testing tool (https://search.google.com/structured-data/testing-tool).
> [rdf] Include JSON-LD in pages

- modules/mod_ginger_edit/templates/_action_ginger_dialog_new_rsc_tab.tpl
Removed callback from new rsc template since there is now a live template to show the connected resources. This callback was from a previous version.
> Fix ginger edit connection new rsc

- modules/mod_ginger_base/templates/search-suggestions/search-query.tpl
Search suggestions are never paged  results. Non paged queries are faster.
> [search] optimize search suggestions

- modules/mod_ginger_remark/templates/remark/remark-view.tpl
* This was broken in #195.
* This PR drops the fallback to creator.
* Remain compatible with anonymous remarks imported from Anymeta.
> [remark] Fix e-mail link missing for anonymous user

- Makefile
I think this is a little less frustrating than having to restart and rebuild all the containers on every DB import.
> Importing a db should not stop zotonic but only the site

- modules/mod_ginger_remark/templates/_remarks.tpl
- modules/mod_ginger_remark/templates/_script.tpl
- modules/mod_ginger_remark/templates/_tinymce_overrides.tpl
- modules/mod_ginger_remark/templates/remark/remark-edit.tpl
Fix #266.
* Remove from _script.tpl, as it's loaded on all pages.
* Move overrides to custom template.
> [remark] Do not load TinyMCE JS on all pages

- .travis.yml
Ginger is now dependent on mod_elasticsearch.
> Clone mod_elasticsearch to fix Ginger build

- .gitignore
- Makefile
- README.md
- docker-compose.yml
- docs/browser-tests.md
- tests/features/step_definitions/assertions.js
- tests/features/step_definitions/forms.js
- tests/features/step_definitions/hooks.js
- tests/features/step_definitions/login.js
- tests/features/step_definitions/navigation.js
- tests/globals.js
- tests/nightwatch.conf.js
- tests/nightwatch.json
- tests/package.json
This PR adds an automated browser testing setup POC.
1. This setup is based on JavaScript, as that makes it independent from the backend stack (Erlang for Ginger sites, PHP for some other projects, external APIs for SPAs). JavaScript is the common denominator between our projects. Moreover, it’s the browser’s language.
2. I opt for Selenium WebDriver instead of a headless NodeJS browser (such as PhantomJS). While PhantomJS will execute tests faster, it makes them fail randomly and thus raise tests maintenance costs. Later, when Chrome headless is stable, we should be able to migrate to that relatively easily. 
3. Tests must work both locally (with a view on the automated browser) and on CI for validation.
4. Tests will be stored in each site’s repository, so they’ll be visible to …
> Add automated browser tests

- modules/mod_ginger_base/templates/search.tpl
Is this ok? "Search | seach word" or do you want "search word | Search"?
> [base] search word in title on search page

- modules/mod_ginger_edit/templates/_admin_tinymce_overrides_js.tpl
- modules/mod_ginger_remark/templates/_tinymce_overrides.tpl
Currently it it impossible to override tinymce templates within site level. The override templates are all included with the editor.
The all include loads the site template first, then the module template. So the options in the module template can never be changed by the site template.
The idea is that we can set a parameter on site level and check that on module level to see if the module should add configuration or not.
> Restructure config override files so it can be overwritten on site level

- modules/mod_ginger_edit/templates/_admin_tinymce_overrides_js.tpl
Setting the admin language switch to another language then nl/en/ru causes a 404 on
/lib/js/tinymce-4.3.7/tinymce/plugins/langs/##.js
there are only 3 language javascripts
> Languages other then en/nl/ru default to en

- Makefile
This seems to reduce CPU usage when running the Gulp container (`$ make gulp site=...`). 
Ref #320.
> [docker] Mount volumes delegated in Gulp container

- modules/mod_ginger_collection/lib/css/src/blocks/_record-meta.scss
- modules/mod_ginger_collection/templates/collection/metadata/geo.tpl
This solves the problem: map block overflows block underneath.
> [collection] Set fixed height to map

- skel/gulpfile.js
- skel/package.json
This PR updates the the Ginger skeleton used when creating a new site at `make addsite`
**Added features**
- Livereload scss, js, and tpl files
- Transpiles javascript to the last two browser versions
- Minify javascript
It also adds the two default `/lib/css/src/screen.scss` and `/lib/js/src/script.js` files.
The package.json has been updated with 
```    
"name": "ginger",
"version": "1.0.0",
"description": "Ginger skeleton",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1",
"start": "gulp",
"build": "gulp sass"
},
"author": "Driebit",
"license": "UNLICENSED",
```
And the `dependencies` renamed to `devDependencies`
> New Gulp setup

- modules/mod_ginger_rdf/README.md
- modules/mod_ginger_rdf/mod_ginger_rdf.erl
This observer caused the dynamically retrieved rdf property to be persisted in the database, causing problems with storage in our search index.
BC break: `m.rdf[id.rdf]` is no longer supported. Use `m.rdf[id]` instead.
> [rdf] Remove legacy observe_rsc_get for RDF property

- modules/mod_ginger_base/lib/js/search/components/filter-terms.js
Keep facets' checked state (through the URL hash) between page loads.
> [base] Fix search facet values state lost

- .dockerignore
- docker/prod/Dockerfile
- docker/prod/etc_zotonic/erlang.config
- docker/prod/etc_zotonic/zotonic.config
- docker/prod/s6/zotonic/run
So we get automatically tagged Docker builds when Ginger itself is
tagged.
This replaces https://github.com/driebit/docker-ginger
> [docker] Build driebit/ginger from main repo

- modules/mod_ginger_base/templates/page-actions/page-action-rsvp.tpl
The current condition for showing the RSVP button on an event's page leads to it only being visible on the last day of the event. This version seems to correct the logic: If the event is not finished yet, you can still add/change your RSVP.
> [base] Fix condition for showing rsvp button

- modules/mod_ginger_rdf/mod_ginger_rdf.erl
- modules/mod_ginger_rdf/templates/_media_upload_panel_rdf.tpl
* By default, don't close modal after a resource has been added.
* This yields the same UX as we already had for adding internal media.
* Make 'OK' button primary after changes in the modal so it's clear for
users what their next step is.
> [rdf] Implement autoclose in find RDF dialog for UX consistency

- modules/mod_ginger_foundation/templates/_script.tpl
If left as is at v3 it will try to use v3.32 resulting in the following error:
```
js?key=…&language=nl&v=3:40 Uncaught TypeError: Cannot read property 'removeChild' of null
at MarkerLabel_.onRemove (scripts.min~49189727.js:1936)
at qu.ug (overlay.js:4)
at su (overlay.js:1)
at Object.xk (overlay.js:5)
at js?key=…language=nl&v=3:146
at Object._.S (js?key=…&language=nl&v=3:62)
at MarkerLabel_._.ag.map_changed (js?key=…language=nl&v=3:146)
at Lc (js?key=…&language=nl&v=3:51)
at MarkerLabel_._.m.set (js?key=…language=nl&v=3:120)
at MarkerLabel_.setMap (js?key=…&language=nl&v=3:54)
```
Also see https://github.com/googlemaps/v3-utility-library/issues/393
> [foundation] Pin google maps version to v3.31 as v3.32 is troublesome

- modules/mod_ginger_rdf/templates/_action_dialog_connect_tab_find_linked_data_results.tpl
This id was duplicated when multiple results lists are shown in the
'add edges' dialog. The id isn't used anyway, so just remove it.
> [rdf] Remove duplicate DOM id

- modules/mod_ginger_base/models/m_ginger_rsc.erl
- modules/mod_ginger_rdf/include/rdf.hrl
- modules/mod_ginger_rdf/models/m_rdf.erl
- modules/mod_ginger_rdf/models/m_rdf_export.erl
- modules/mod_ginger_rdf/support/dcterms.erl
- modules/mod_ginger_rdf/support/ginger_json_ld.erl
- modules/mod_ginger_rdf/support/rdf_ontology.erl
- modules/mod_ginger_rdf/support/rdf_property.erl
- modules/mod_ginger_rdf/support/schema_org.erl
- modules/mod_ginger_rdf/templates/mediaclass.config
- modules/mod_ginger_rdf/tests/mod_ginger_rdf_tests.erl
* Move RDF export logic into new m_rdf_export module.
* Add rdf_ontology behaviour and schema_org as the first implementation.
* Export content in all available languages instead of only the default one.
* Add more tests.
> [rdf] Add schema.org RDF serialization

- modules/mod_ginger_base/controllers/controller_rest.erl
The return value of `path_to_id ` has an integer, so `list_to_integer ` crashes
> [base] Fix path to id conversion in REST api

- modules/mod_ginger_base/controllers/controller_rest.erl
Check if custom property exists before encoding and adding it to the resources.
> [base] Check if custom property exists on resource

- docs/rest-api.yaml
- modules/mod_ginger_base/controllers/controller_rest.erl
We're currently missing the predicates of edges, which makes them quite useless.
With this method it's possible to send the same resource multiple times in a single request. 
- Update docs
> [WIP] Include predicate name in Edge Object

- modules/mod_ginger_base/mod_ginger_base.erl
If ACL rules disallow anonymous users from viewing a resource, the
m_rsc:p/3 in the custom pivot observer returns undefined instead of the
actual value for that resource.
> [base ] Fix is_unfindable not pivoted if resource is inaccessible

- modules/mod_ginger_base/controllers/controller_rest.erl
Patternmatching the `id` from the path will return a string, we want an integer.
> Convert path ids to integers

- modules/mod_ginger_base/filters/filter_https.erl
So don't crash when |https is called on an empty value in templates.
> [base] Accept empty values as input to filter_https

- docker-compose.yml
The previous elasticsearch version crashes almost immediatly on my system.
I don't know the exact cause, but a (small) version bump fixed the issue.
Because we use ES v5.3.2 in our production environments too I picked that
version to use here.
> Bump Elasticsearch version in Docker Compose file

- modules/mod_ginger_edit/templates/_editor.tpl
- modules/mod_ginger_remark/templates/remark/remark-edit.tpl
This was broken in #267, where subject_id was defaulted to id instead of
the_remark_id, because the zmedia and zlink wires in remark-edit.tpl were
overridden by those in _editor.tpl.
> [remark] Fix media upload by passing remark_id as subject_id

- modules/mod_ginger_embed/mod_ginger_embed.erl
This fixes: duplicate key value violates unique constraint
\"config_module_key_key\"">>,[{detail,
<<"Key (module, key)=(site, html_elt_extra) already exists.">>}]
This is already configured in mod_ginger_base, so no need to duplicate
it here.
> [embed] Fix duplicate key html_elt_extra

- modules/mod_ginger_rdf/mod_ginger_rdf.erl
This is necessary because mod_ginger_rdf:manage_schema/2 creates a
subcategory of content_groups, which must therefore be created first.
> [rdf] Add dependency to mod_content_groups

- modules/mod_ginger_base/templates/admin_seo.tpl
- modules/mod_ginger_base/translations/nl.po
* Read the noindex param only from the site/config file, not from the 
database.
* When disabled, saving the form will not persist a value for noindex
in the database. This means the value from site/config will always be
leading.
> [base] Disable the noindex checkbox in the admin

- .travis.yml
- modules/mod_ginger_base/models/m_ginger_rest.erl
- modules/mod_ginger_base/tests/m_ginger_rest_tests.erl
This fixes a bug introduced in #473.
* Translated properties were causing jsx:encode to fail.
* Add test.
> [base] Fix REST API blocks output

- skel/SITE.erl
* Changing the version creates trouble when switching branches (that
have a lower version), as schema downgrades are not supported.
* It's good practice to have an idempotent schema instead of versions,
anyway.
* schema:reset/1 always runs when deploying sites (in .gitlab-ci.yml),
so the only (but significant!) downside of this is the fact that
developers must remember to run schema:reset/1 locally.
> [skel] Don't change mod_schema version

- modules/mod_ginger_collection/support/collection_query.erl
For erfgoedbrabant ticket: https://mantis.driebit.nl/view.php?id=27791
Currently only http://www_europeana_eu/schemas/edm/isShownBy.@id is mapped to depiction, some datasets also use: http://www_europeana_eu/schemas/edm/isShownBy.@value
> [collection] Add isShownBy.@value to depiction fields

- modules/mod_ginger_base/templates/search-suggestions/search-query.tpl
* This way, users get results for partial queries, too.
* Only search in fields that are shown in the suggestion results, i.e.
title*.
* See https://github.com/driebit/mod_elasticsearch/#extra-query-arguments
> Use prefix query for search suggestions

- modules/mod_ginger_edit/templates/_logon_error.tpl
The `_logon_error.tpl` is overruled in ginger, so the ratelimit error was not shown.
(Note: the best solution is to overrule less templates...)
> Show 'ratelimit' error.

- Makefile
- README.md
- config/zotonic.config
This adds a hybrid Docker setup that is compatible with the full Docker setup. Zotonic itself runs directly on the host, communicating with containers running Postgres and Elasticsearch.
> [doc] Document selective Docker

- modules/mod_ginger_base/models/m_ginger_rest.erl
Query sometimes returns `<<>>`
> Check if blocks is empty binary

- modules/mod_ginger_base/controllers/controller_rest_resources.erl
- modules/mod_ginger_base/models/m_ginger_rest.erl
This makes lookups for resources with a fixed name easier, e.g.
http://site/data/resources/some_resource instead of
http://site/data/resources/123456.
> [base] Support unique name as argument to REST endpoint

- modules/mod_ginger_base/models/m_ginger_rest.erl
- modules/mod_ginger_base/tests/m_ginger_rest_tests.erl
There is no method of filling these fields so no reason include these in the response
> [base] Remove header and style from blocks

- modules/mod_ginger_base/controllers/controller_search.erl
If returned search facets for controller_search:to_json are undefined, use empty list
> [base] Handle undefined facets in search results for controller_search

- modules/mod_ginger_base/controllers/controller_rest_resources.erl
Since there is no PATCH method we use post.
Posting at `/data/resources/id` will update the resource at `id`
> [base] Patch resource via REST api

- modules/mod_ginger_base/controllers/controller_auth.erl
Whenever an error is returned to the user, the error is set as the response
body. However, some of these errors are returned as atoms, not binaries or
strings. This causes `set_resp_body` to fail, resulting in a 500 error and no
response body. This commit remedies that.
> Make sure response bodies are strings (lists)

- modules/mod_ginger_rdf/support/dbpedia.erl
This filter prevented us from seeing useful data, and the check for the wiki
link is done in the templates as well, so is unnecessary here.
> Remove unnecessary 'isPrimaryTopic' filter from DBpedia Sparql query

- modules/mod_ginger_base/templates/search-suggestions/search-query.tpl
Search query now gives no results back, with text it does. Prefix is old this was also fixed in the other search query template.
> [Base] Refactor prefix to text in search

- modules/mod_ginger_base/lib/js/search/search_ui.js
When there zero facets in the searchwidgets the search would break since it can't find facets
> [base] Add check around getFacets

- modules/mod_ginger_base/models/m_ginger_rest.erl
Don't unescape translated texts
> [base] Escape html in Ginger Rest API

- modules/mod_ginger_collection/support/collection_query.erl
For ErfgoedBrabant project we need hasView property to be within "with media" selection (filter edge depiction). see https://mantis.driebit.nl/view.php?id=28054 for more background information.
> [Collection] Add hasView property to depiction edge mapping

- modules/mod_ginger_base/controllers/controller_auth.erl
Return `{status: anonymous}` instead of a http error if you're not signed in.
You're allowed to get the status, even if it's anonymous.
This also prevents logging console errors in the browser every time you load the page.
> [base] Return 200 with object on GET auth status request instead of http error

- modules/mod_ginger_base/controllers/controller_auth.erl
Fixes 
```
XML Parsing Error: not well-formed
Location: http://oog.docker.test/data/auth/status
Line Number 1, Column 1:
```
> [base] Fix missing Content-Type by use Req in return value of to_json

- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect.tpl
This is to support tab order as requested in issue OR-308.
I checked the Ginger sources and this would not change any default tab order used there.
> Use tabs_enabled to define the order of the default find/new/upload/url tabs.

- modules/mod_ginger_edit/templates/_ginger_edit_js_include.tpl
This is needed to support mod_geomap in ginger-edit (as ginger edit does not have the include all of `_js_admin.tpl`)
> Include geomap js on ginger-edit page.

- skel/support/SITE_data_fixtures.erl
- ACL fixtures should only and always be implemented in the prod fixtures
> [Skel] Remove ACL fixtures from dev data

- modules/mod_ginger_rdf/support/ginger_json_ld.erl
- modules/mod_ginger_rdf/tests/m_rdf_tests.erl
- modules/mod_ginger_rdf/tests/mod_ginger_rdf_tests.erl
- scripts/runtests.sh
All predicates should contain lists of objects; see
https://w3c.github.io/json-ld-syntax/#expanded-document-form.
> [rdf] Export JSON-LD consistently in expanded form

- modules/mod_ginger_rdf/support/ginger_json_ld.erl
- modules/mod_ginger_rdf/tests/mod_ginger_rdf_tests.erl
We used to produce JSON-LD documents like:
```
"@type": {
"@id": "http://..."
}
```
However, this doesn't validate against https://json-ld.org/playground/, so change it to:
```
"@type": ["http://..."]
```
which does validate.
> [rdf] Fix JSON-LD type serialization

- modules/mod_ginger_base/lib/js/global-nav.js
Refactor size function to length, .length property is preferred because it does not have the overhead of a function call
> [Base] Fix js error in global nav

- modules/mod_ginger_base/controllers/controller_search.erl
Added to the search api endpoint
The resources endpoint continues to return resources that have `is_unfindable` set to `true`
> Always filter resources that have is_unfindable=true

- config/zotonic.config
- docker/prod/etc_zotonic/zotonic.config
Zotonic 0.x now depends on jsx 3.0.0
> Remove jsx dependency from docker and sample config

- modules/mod_ginger_rdf/support/ginger_json_ld.erl
- modules/mod_ginger_rdf/templates/_html_head.tpl
- modules/mod_ginger_rdf/templates/_html_head_ginger_rdf.tpl
* Adds '_html_head_ginger_rdf.tpl' for easier overrule of the json-ld link.
* Better error message on missing namespace.
> mod_ginger_rdf: split _html_head.tpl

- modules/mod_ginger_rdf/README.md
- modules/mod_ginger_rdf/models/m_rdf_export.erl
We already publish RDF only for visible (published) subject resources, 
so do the same for any edges in those resources: filter them by visibility.
> [rdf] Export only visible edges

- modules/mod_ginger_rdf/include/rdf.hrl
This is used for nested resources that have blank nodes.
> [rdf] Make explicit that triple object can be a resource

- modules/mod_ginger_base/support/ginger_http_client.erl
- modules/mod_ginger_rdf/models/m_dbpedia.erl
This fixes an issue where keyword metadata is not show if nl.dbpedia.org is down.
> mod_ginger_rdf: add caching of dbpedia lookups in the tkvstore.

- modules/mod_ginger_rdf/README.md
- modules/mod_ginger_rdf/controllers/controller_hydra.erl
- modules/mod_ginger_rdf/controllers/controller_rdf.erl
- modules/mod_ginger_rdf/dispatch/dispatch
- modules/mod_ginger_rdf/include/rdf.hrl
- modules/mod_ginger_rdf/support/cors_headers.erl
- modules/mod_ginger_rdf/support/ginger_json_ld.erl
- modules/mod_ginger_rdf/support/ginger_turtle.erl
- modules/mod_ginger_rdf/support/rdf_property.erl
* Add a controller at `/hydra/123` that serializes Zotonic queries
as Hydra collections, either in JSON-LD or Turtle.
* Hydra gives machine-readable pagination over large collections.
See﻿ https://www.hydra-cg.com/spec/latest/core/.
* Filter out empty triple objects in both JSON-LD and Turtle serializations.
This makes it easy to dump some triples that may not have a value,
such as previous or next page in our case. 
* The `/hydra` endpoint can be used as the RDF distribution of datasets,
which are a subcategory of `query`. 
* Add documentation.
> [rdf] Serialize queries as Hydra collections

- modules/mod_ginger_rdf/controllers/controller_hydra.erl
- modules/mod_ginger_rdf/controllers/controller_rdf.erl
- modules/mod_ginger_rdf/dispatch/dispatch
* Keep `ontology` for BC with existing dispatch rules in sites.
> [rdf] Support multiple ontologies in controllers

- modules/mod_ginger_base/lib/js/search-suggestions.js
Implemented for Rietveld. After that site has updated to the a ginger version including this commit, the workaround in commit 893baf8f00ea6d628e58a28779caab0b8ee13cc6.
> Make search function properly with tab navigation

- modules/mod_ginger_base/models/m_ginger_rest.erl
As the resource unique name is a core concept and tool within Zotonic/Ginger domain modelling it is quite surprising that it wasn't included in the resource representations yet. Did I miss anything that opposes inclusion of the resource unique name?
> [base] Include unique name in /data/resources output

- modules/mod_ginger_base/support/ginger_search.erl
This allows for querying resources having subjects or objects with a specific predicate (e.g. `haspart`).
> Allow for the predicate to be specified in hassubjects and hasobjects queries

- modules/mod_ginger_base/lib/js/search-suggestions.js
- modules/mod_ginger_base/templates/search-suggestions/toggle-search.tpl
This fixes Mantis 30804 and adds proper tabbing behaviour to the standard Ginger search bar:
1. Enter on search button opens the search bar
2. Pressing tab in the search bar closes the search bar (navigate search suggestions with arrow keys)
3. Search input cannot be focused when it's hidden
4. Ensure search toggle is focusable in Safari (Fix from Rietveld for Mantis 30717)
> Fix search suggestions not being clickable

- modules/mod_ginger_base/lib/js/search/search_ui.js
Using the ginger_search_hash scomp, we can link to search pages with certain filters applied. However facets would not be loaded. This change fixes that.
> Add facets to query parameters on non-empty search hash

- modules/mod_ginger_base/templates/pager/pager.tpl
- modules/mod_ginger_base/translations/nl.po
This fixes a problem where the pager displays an amount of hits that seems to be very accurate, which gives the suggestion that the displayed number is exact when in fact it is an estimate.
Also update the NL translations.
(Needs the 0.71 or 0.x branch for the `round_significant` filter)
> mod_ginger_base: show in pager if result count is an estimate

- modules/mod_ginger_adlib_elasticsearch2/mod_ginger_adlib_elasticsearch2.erl
- modules/mod_ginger_collection/filters/filter_collection_object_url.erl
- modules/mod_ginger_collection/models/m_collection_object.erl
- modules/mod_ginger_collection/templates/collection/list/list-item-carousel.tpl
- modules/mod_ginger_collection/templates/collection/list/list-item.tpl
- modules/mod_ginger_collection/templates/collection/prevnext.tpl
- modules/mod_ginger_collection/templates/search-suggestions/search-suggestions.tpl
Add support for mod_elasticsearch2 to the Adlib/collection modules.
In ES7+ the _type is removed, as we used it for the Adlib database reference when storing documents we now have to combine the type and priref of a record to make an unique document `_id`  (as multiple databases can have the same priref).
The filter `collection_object_url` can now be used to make `collection_object` urls, this instead of manually combining the type and id in the template (or Erlang code).
See also: https://github.com/driebit/mod_elasticsearch2/pull/5
> Elasticsearch2 Adlib support

- modules/mod_ginger_base/lib/js/search/search_ui.js
- modules/mod_ginger_base/scomps/scomp_ginger_base_ginger_search_hash.erl
Instead of base64 encoding, which would fail on non ASCII characters
> Use URI encoding for search state

- modules/mod_ginger_base/templates/search/search-query.tpl
The filters query term was not passed to the ginger_search query.
This fixes IES-1
> Search query filters

- modules/mod_ginger_collection/models/m_collection_object.erl
Looking up an object with `m.collection_object["Object"][id]` was broken when id was an elastic2 id (with `::Type` appended). This commit fixes this and allows lookup with `m.collection_object[id]` as well.
> Fix an issue with dynamic elastic-ids

- modules/mod_ginger_rdf/support/dbpedia.erl
As the 'http' site gives timeouts, and it will redirect to 'https' anyway, force metadata lookups to use the 'https' url.
> Fix a problem where nl.wikipedia.org gives timeouts with http (but not https)

- modules/mod_ginger_collection/support/collection_query.erl
The 'yyyy' format is strict and only accepts a date >= 1000.
The 'year' format is less strict and accepts any integer value.
> mod_ginger_collection: fix filter on dates before the year 1000

- modules/mod_ginger_collection/models/m_collection_object.erl
The fetch document routine is also frequently used to check _if_ a document is present.
That check now generates a log entry, which is somewhat unexpected.
> mod_ginger_collection: set enoent doc warning to 'debug' level

- modules/mod_ginger_base/templates/head/head.tpl
- modules/mod_ginger_base/templates/head/polyfill.tpl
See the issue: [OEI-128](https://driebit.atlassian.net/browse/OEI-128)
For reference, see: https://sansec.io/research/polyfill-supply-chain-attack
> Replace polyfill.io with fastly's alternative

- modules/mod_ginger_rdf/support/ginger_json_ld.erl
- When in a json+ld response the @context is top-level and multiple subjects are described in the @graph part, pass on the context into the recursion. Also, if a local @context is found in the description of a single subject, let it override (merge with) the global context, as expected.
- Let the caller of deserialize specify an id where the call was done for - so if multiple subjects are described we can pick the right one for top level.
> [mod_ginger_rdf] Make parser more robust against variants of nesting

- modules/mod_ginger_base/support/ginger_uri.erl
Expected to fix site breakage, where this typo appeared in an rdf resource.
> [mod_ginger_base] Force httpss (note the extra s) links to https

- modules/mod_ginger_base/support/ginger_http_client.erl
- modules/mod_ginger_base/support/ginger_uri.erl
- modules/mod_ginger_rdf/models/m_dbpedia.erl
- modules/mod_ginger_rdf/support/dbpedia.erl
- modules/mod_ginger_rdf/support/sparql_client.erl
When fetching a resource from dbpedia, and If a predicate is present in multiple languages, then these languages are mixed in all rows of the search results.
It looks like a kind of combinatorial explosion of all language values.
Ideally the spqarql query should group by language of the returned predicates.
As that doesn't seem to be trivial, we now group the returned predicates by language and try to find the _best matching_ triple value for the requested language.
> ZZCS-33 Fix a problem where incorrect language results would be returned for dbpedia fetches

- modules/mod_ginger_foundation/lib/css/src/_base.scss
- modules/mod_ginger_foundation/lib/css/src/_buttons.scss
- modules/mod_ginger_foundation/lib/css/src/_form.scss
- modules/mod_ginger_foundation/lib/css/src/_variables.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_category-of.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_content-group-nav.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_global-search.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_list.scss
- modules/mod_ginger_foundation/lib/css/src/layout/_global-nav.scss
- modules/mod_ginger_foundation/lib/css/src/pages/_edit.scss
- modules/mod_ginger_foundation/lib/css/src/pages/_search.scss
Remove:
- darken(...)
- lighten(...)
in favor to css color-mix()
> Refactor SCSS color definitions to use color-mix removing deprecated sass

- modules/mod_ginger_base/mod_ginger_base.erl
Moderator can use mod_admin_identity for user management reasons. Part of user management is adding/removing user groups to a user. Yet not be able to change to/from managers user group.
Giving access to the whole mod_acl_user_group seems to have more consequences then just managing user groups.
> Add ACL rule for insert/delete user group
