- modules/mod_ginger_auth/mod_ginger_auth.erl
> [auth] Fix reload page after logon on unauthorized page

- modules/mod_ginger_base/templates/error.tpl
> add stylng to 404 page

- modules/mod_ginger_base/lib/js/global-nav.js
- modules/mod_ginger_foundation/lib/css/src/layout/_global-nav.scss
> make menu dropdowns work on tablets Fix #123

- Makefile
See also https://github.com/zotonic/zotonic/issues/1321.
> Remove mnesia directory to fix filezcache boot failure

- modules/mod_ginger_github/LICENSE
- modules/mod_ginger_github/README.md
- modules/mod_ginger_github/mod_ginger_github.erl
- modules/mod_ginger_github/models/m_github.erl
- modules/mod_ginger_github/models/m_zenhub.erl
- modules/mod_ginger_github/support/ginger_http_client.erl
- modules/mod_ginger_github/support/github_client.erl
- modules/mod_ginger_github/support/json_parser.erl
- modules/mod_ginger_github/support/zenhub_client.erl
- modules/mod_ginger_github/templates/_admin_configure_module.tpl
> github: Add mod_ginger_github

- modules/mod_ginger_edit/lib/css/src/_base.scss
- modules/mod_ginger_foundation/lib/css/src/_base.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_comments.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_list.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_person.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_remarks.scss
- modules/mod_ginger_foundation/lib/css/src/layout/_content.scss
- modules/mod_ginger_foundation/lib/css/src/layout/_footer.scss
- modules/mod_ginger_foundation/lib/css/src/layout/_survey.scss
- modules/mod_ginger_foundation/lib/css/src/pages/_search.scss
Hey @DorienD kun je even kijken of deze aanpassingen kloppen?
> CSS errors eruit

- docs/guidelines.md
Now we have a roadmap (#139), we need to make sure it shows all significant changes.
@Dirklectisch I understand you already had some discussion about this with @eminetuzkapan. This is my proposed solution.
> Add creating issues to guidelines

- modules/mod_ginger_cookie_consent/LICENSE
- modules/mod_ginger_cookie_consent/README.md
- modules/mod_ginger_cookie_consent/lib/css/cookie-consent.css
- modules/mod_ginger_cookie_consent/mod_ginger_cookie_consent.erl
- modules/mod_ginger_cookie_consent/templates/_html_head.tpl
- modules/mod_ginger_cookie_consent/templates/_script.tpl
- modules/mod_ginger_cookie_consent/templates/cookie-consent-config.tpl
- modules/mod_ginger_cookie_consent/templates/cookie-consent.tpl
- modules/mod_ginger_cookie_consent/translations/nl.po
> Add mod_ginger_cookie_consent

- modules/mod_ginger_base/templates/attached-media/attached-media-thumb.document.tpl
Fixed the problem with pdf preview being a fixed width, causing it to overflow its boundaries.
> 170 pdf preview to fit in page

- docker-compose.yml
- docs/docker.md
> [docker] Set up Docker containers for Elasticsearch

- modules/mod_ginger_remark/templates/remark/remark-view.tpl
@DorienD can you check if I did it right?
> [remark] Don't link to the anonymous user

- modules/mod_ginger_base/templates/masthead/masthead.tpl
- modules/mod_ginger_foundation/templates/mediaclass.config
> 191 masthead image without cropping

- Makefile
- docker-compose.yml
- docs/docker.md
- docs/guidelines.md
- skel/.editorconfig
- skel/.gitignore
- skel/SITE.erl
- skel/config.in
- skel/gulpfile.js
- skel/package.json
> Add site skeleton

- modules/mod_ginger_remark/templates/remark/remark-list.tpl
I guess this is generally good practice.
> [remark] Add ACL check around 'add remark' button

- modules/mod_ginger_base/support/ginger_geo_search.erl
- modules/mod_ginger_base/support/ginger_search.erl
* Replace call to search_query:search with notification.
* Make sure to remove all custom search arguments, as Zotonic
will trip over them.
> [base] Make Ginger search open for extension

- modules/mod_ginger_base/templates/masthead/masthead.tpl
A check if the parent or the rsc has a banner or depiction to use as a header
> Masthead checks parent masthead image

- modules/mod_ginger_remark/mod_ginger_remark.erl
> Author notification when new remark is posted

- modules/mod_ginger_base/lib/js/back-to-top.js
- modules/mod_ginger_base/templates/back-to-top/back-to-top-link.tpl
- modules/mod_ginger_base/translations/nl.po
- modules/mod_ginger_collection/templates/_script.tpl
- modules/mod_ginger_collection/templates/page.beeldenzoeker.tpl
- modules/mod_ginger_foundation/lib/css/src/blocks/_back-to-top.scss
- skel/package.json
Make back to top functionality, originally developed for mod_ginger_collection, generic and move it into base/foundation. 
Replaces #274.
> [base] Add back to top

- modules/mod_ginger_collection/lib/css/src/blocks/_adlib-actions.scss
- modules/mod_ginger_collection/lib/css/src/blocks/_list.scss
- modules/mod_ginger_collection/lib/css/src/blocks/_masthead.scss
- modules/mod_ginger_collection/lib/css/src/blocks/_readmore.scss
- modules/mod_ginger_collection/lib/css/src/blocks/_record-meta.scss
- modules/mod_ginger_collection/lib/css/src/pages/_adlib-object.scss
- modules/mod_ginger_collection/templates/beeldenzoeker/metadata/geo.tpl
- modules/mod_ginger_collection/templates/beeldenzoeker/readmore.tpl
- modules/mod_ginger_collection/templates/beeldenzoeker/record-meta.tpl
- modules/mod_ginger_collection/templates/list/list-item-beeldenzoeker.tpl
Please check if this is the correct solution to conditionally rendering the metadata element.
https://github.com/driebit/ginger/commit/c6fee9b2fe1f84cec49eba0be00fdc82699e7cc3
> [collection] Object page styling

- modules/mod_ginger_base/templates/page-actions/page-action-add-thing.tpl
- modules/mod_ginger_edit/mod_ginger_edit.erl
- modules/mod_ginger_edit/templates/_action_ginger_connection.tpl
- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect.tpl
- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect_tab_find.tpl
- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect_tab_find_results.tpl
- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect_tab_find_results_loop.tpl
These changes add all templates and erlang to handle custom filtering in the connect dialog.
> Contentgroup filter connect dialog

- modules/mod_ginger_base/lib/js/carousel.js
- modules/mod_ginger_base/templates/carousel/carousel.tpl
Old situation default settings would override the current settings.
> [base] Fixed carousel js implementing the wrong settings

- modules/mod_ginger_foundation/lib/css/src/_mixins.scss
This will simply of adding pseudo elements over and over again when changing styling on an anchor tag.
> [foundation] Simplified changing anchor styling

- modules/mod_ginger_rdf/support/ginger_json_ld.erl
As discussed an extra lookup for aliases in the json-ld context.
> Resolve predicate alias in json-ld context

- modules/mod_ginger_base/templates/head/head.tpl
- modules/mod_ginger_collection/filters/filter_collection_query_offset.erl
- modules/mod_ginger_collection/filters/filter_collection_query_pager.erl
- modules/mod_ginger_collection/lib/css/src/blocks/_adlib-description.scss
- modules/mod_ginger_collection/lib/css/src/blocks/_collection-nav.scss
- modules/mod_ginger_collection/lib/css/src/pages/_adlib-object.scss
- modules/mod_ginger_collection/templates/collection/list/list-item.tpl
- modules/mod_ginger_collection/templates/collection/prevnext.tpl
- modules/mod_ginger_collection/templates/collection/search-query.tpl
- modules/mod_ginger_collection/templates/list/list-items.tpl
- modules/mod_ginger_collection/templates/page.collection_object.tpl
Added collection navigation. Part of https://gitlab.driebit.nl/driebit/zuiderzeecollectie/merge_requests/10
> [collection] ZZC-57 Added collection navigation

- .travis.yml
- modules/mod_ginger_collection/filters/filter_iso8601.erl
- modules/mod_ginger_collection/tests/mod_ginger_collection_tests.erl
> [collection] Improve iso8601 date filter

- modules/mod_ginger_base/support/ginger_geo_search.erl
* Re-use Zotonic's geo search instead of duplicating the code.
Fix #370.
> [base] Fix ginger_geo_nearby with negative lat/lng

- modules/mod_ginger_base/filters/filter_exclude_property.erl
* For filtering on (e.g.) URIs.
> [base] Add exclude_property filter

- modules/mod_ginger_activity/README.md
- modules/mod_ginger_activity/dispatch/dispatch
- modules/mod_ginger_activity/include/ginger_activity.hrl
- modules/mod_ginger_activity/mod_ginger_activity.erl
- modules/mod_ginger_activity/models/m_ginger_activity.erl
- modules/mod_ginger_activity/models/m_ginger_activity_inbox.erl
- modules/mod_ginger_activity/services/service_ginger_activity_inbox.erl
* Add HTTP API for getting and deleting items from the user's activity stream.
* BC break: #entry{} was renamed to #ginger_activity{}.
* Add documentation in readme.
* Apply mod_ginger_template template to README.md.
Depends on https://github.com/zotonic/zotonic/pull/1904 for DELETE requests.
> [activity] Add activity inbox

- modules/mod_ginger_collection/templates/collection/creator.tpl
* Fix DBpedia thumbnail. The SPARQL DESCRIBE returns the DBpedia
thumbnail in multiple triples, so assume a list and take the first.
* Truncate RKD artist qualification.
* Fix artist death date display.
> [collection] Improve artist details from RKD and DBpedia

- .travis.yml
- modules/mod_ginger_activity/include/ginger_activity.hrl
- modules/mod_ginger_activity/mod_ginger_activity.erl
- modules/mod_ginger_activity/models/m_ginger_activity.erl
- modules/mod_ginger_activity/models/m_ginger_activity_inbox.erl
- modules/mod_ginger_activity/services/service_ginger_activity_inbox.erl
- modules/mod_ginger_activity/tests/mod_ginger_activity_tests.erl
* Add to property.
* Add integration test.
* Prepare for activity as an opaque type (best practice for records) by moving record generation into the model (m_ginger_activity).
> [activity] Add 'to' (primary audience) for mentions

- modules/mod_ginger_rdf/support/rdf_property.erl
* Prefer function calls over macros.
> [rdf] Add functions for constructing RDF properties

- modules/mod_ginger_rdf/include/rdf.hrl
- modules/mod_ginger_rdf/models/m_rdf.erl
- modules/mod_ginger_rdf/models/m_rdf_export.erl
- modules/mod_ginger_rdf/tests/mod_ginger_rdf_tests.erl
* Tweak some type definitions.
* Remove unused function publisher_triples/1
> [rdf] Only export type if category has URI

- modules/mod_ginger_rdf/support/schema_org.erl
* Export both body and summary.
* Export subject edges.
* Accept invalid user-defined dates.
> [rdf] Improve schema.org output

- modules/mod_ginger_dbpedia_spotlight/support/ginger_dbpedia_spotlight_client.erl
See https://www.dbpedia-spotlight.org/api
> Update DBpedia Spotlight API URL

- modules/mod_ginger_edit/controller/controller_ginger_edit.erl
- modules/mod_ginger_edit/dispatch/dispatch
> [edit] Don't redirect to custom URL

- skel/Makefile
Follows these https://guide.elm-lang.org/optimization/asset_size.html instructions for smallest asset size
> [skel] Use recommended uglify config in skel, add DIST_DIR variable

- modules/mod_ginger_remark/mod_ginger_remark.erl
> [remark] Fix #453: don't force site language to NL

- skel/SITE.erl
- skel/support/SITE_data_fixtures.erl
Add standard data fixtures file
> [skel] Add data fixtures

- modules/mod_ginger_base/models/m_ginger_rest.erl
Custom page_urls aren't checked when using m_rsc:page_url
> [base] Use page_path for page and fallback to page_url

- modules/mod_ginger_base/controllers/controller_auth.erl
- modules/mod_ginger_base/controllers/controller_login.erl
- modules/mod_ginger_base/dispatch/dispatch
Work in progress and when it is finished we need to discuss security implications.
> [base] Add controller to allow logins from SPAs (e.g. Elm)

- modules/mod_ginger_rdf/controllers/controller_rdf.erl
- modules/mod_ginger_rdf/dispatch/dispatch
- modules/mod_ginger_rdf/mod_ginger_rdf.erl
- modules/mod_ginger_rdf/support/ginger_turtle.erl
- modules/mod_ginger_rdf/tests/mod_ginger_rdf_tests.erl
* Extend controller_rdf to support both JSON-LD and Turtle serialisation.
> [rdf] Add Turtle RDF serialization over HTTP

- modules/mod_ginger_base/support/ginger_utils.erl
- modules/mod_ginger_rdf/models/m_rdf.erl
> [rdf] Preserve order when de-duplicating object ids

- modules/mod_ginger_base/controllers/controller_auth.erl
> [base] Fix wrong identity fetched (#513)

- modules/mod_ginger_base/controllers/controller_auth.erl
Fix #513.
* Use Zotonic API for logging in (z_auth:logon/2) so regular login
notifications are dispatched.
* Call highest-level 'API' available for logging out.
* Initialize session and context in service_available/2.
* Use regular z_acl:user/1 instead of custom user_id session variable.
> [base] Refactor controller_auth

- modules/mod_ginger_base/controllers/controller_auth.erl
Return the user resource _with_ edges. As how is done with the rest controller response.
> [base] Add edges to user resource in auth controller response

- modules/mod_ginger_base/templates/search/components/filter-terms-options.tpl
- modules/mod_ginger_collection/templates/collection/prevnext.tpl
- modules/mod_ginger_collection/templates/collection/search-suggestions/search-query.tpl
- modules/mod_ginger_collection/templates/collection/search/components/filters-license-options.tpl
- modules/mod_ginger_collection/templates/collection/search/components/filters-subjects.tpl
- modules/mod_ginger_edit/templates/_action_dialog_person_connect.tpl
- modules/mod_ginger_edit/templates/_ginger_edit.tpl
- modules/mod_ginger_remark/templates/_remarks.tpl
- modules/mod_ginger_remark/templates/remark/remark.tpl
@ddeboer 
- Heb lokaal nog niet getest, met Krista besproken dit op ginger test te doen
> Escape query parameters

- modules/mod_ginger_base/controllers/controller_search.erl
- modules/mod_ginger_base/support/ginger_search.erl
Also add facet support for the coordinates endpoint
> Add support for fetching publication_start facets

- modules/mod_ginger_edit/templates/_action_ginger_connection.tpl
- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect_tab_find.tpl
So we can customize the message in the dialog find modal.
> Add dynamic helper text for in the find dialog

- modules/mod_ginger_geonames/support/geonames_lookup.erl
* The task callback gets an anonymous Context, which causes geo lookups
to fail on unpublished resources.
* The geo lookup was duplicated anyway, so simplify by passing it to the
callback.
* Introduce type for clarity.
> [geonames] Fix geo lookup for unpublished resources

- modules/mod_ginger_rdf/tests/mod_ginger_rdf_tests.erl
> [rdf] Update test for #537

- modules/mod_ginger_base/models/m_ginger_rest.erl
Because we use the subtitle field often in our sites, would be nice to add it to the api so we don't have to add it in every site individually.
> [base] Add subtitle to rest api

- modules/mod_ginger_base/controllers/controller_auth.erl
We should realllllyyy write some tests...
> Fix a typo in the `wrq:set_resp_body` function call

- modules/mod_ginger_base/controllers/controller_rest_edges.erl
- modules/mod_ginger_base/controllers/controller_rest_resources.erl
- modules/mod_ginger_base/dispatch/dispatch
> [base] Use propslist in REST dispatch, add is_authorized

- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect.tpl
- modules/mod_ginger_edit/templates/_ginger_edit_depiction.tpl
- This will make sure the oembed tab is included again in the frontend edit or the linked data tabs
- Standardize oembed in frontend depiction relation
> Add all include links for more connection possibilities

- modules/mod_ginger_base/templates/_action_dialog_new_rsc_tab.tpl
- modules/mod_ginger_base/templates/_admin_category_dropdown.tpl
This is fixed in zotonic 0.50.0 (https://github.com/zotonic/zotonic/commit/6113e6655323b62767b9898f2e6967ae0d144659). But we need it sooner.
> [Base] Add a temp fix for category selectbox for internal links

- modules/mod_ginger_base/templates/media/_caption.tpl
> [Base] Fix author bug

- modules/mod_ginger_base/mod_ginger_base.erl
See also https://github.com/zotonic/zotonic/issues/1329.
> [base] Set Strict-Transport-Security HTTP header

- modules/mod_ginger_base/templates/media/media.image.tpl
- modules/mod_ginger_base/templates/media/media.video.tpl
- modules/mod_ginger_foundation/lib/css/src/_base.scss
> add video element to css rules under video-figure__container

- modules/mod_ginger_spa/templates/_admin_tinymce_overrides_js.tpl
- modules/mod_ginger_spa/templates/base.tpl
- modules/mod_ginger_spa/templates/mediaclass.config
- modules/mod_ginger_spa/templates/page.tpl
* Fix language attribute (should be lowercase)
* Remove a11y unfriendly browser scaling
* Render site menus as js objects and pass on to elm as flags
* Add opengraph and twitter card meta tags
* Add charset to properly render ligatures and the like
* Add base.tpl, which loads some zotonic js files needed for public admin pages
* Add mediaclass.config
> [SPA] Mod spa improvements

- modules/mod_ginger_collection/support/collection_query.erl
- modules/mod_ginger_rdf/include/rdf.hrl
Add ACL namespace to the set of namespaces that can be considered the
base set for sites to pick from.
> Fix 'Namespace ... not registered'

- modules/mod_ginger_edit/templates/_action_ginger_dialog_connect.tpl
> [Edit] Add block around extra tabs and panels

- modules/mod_ginger_spa/templates/mediaclass.config
This is a default class in elm-ginger
> [base] Add thumbnail mediaclass

- modules/mod_ginger_foundation/templates/_script.tpl
Google maps api version 3.31 to quarterly with override option
> [foundation] Dynamic google maps api version

- modules/mod_ginger_rdf/include/rdf.hrl
- modules/mod_ginger_rdf/support/ginger_json_ld.erl
- modules/mod_ginger_rdf/support/schema_org.erl
- modules/mod_ginger_rdf/tests/mod_ginger_rdf_tests.erl
* Set date object type to schema:DateTime to make it validate against
https://validator.schema.org.
> [rdf] Support object types and export them

- modules/mod_ginger_rdf/controllers/controller_hydra.erl
- modules/mod_ginger_rdf/controllers/controller_rdf.erl
- modules/mod_ginger_rdf/support/cors_headers.erl
The `Access-Control-Allow-Origin` header was not returned from HTTP
responses.
> [rdf] Fix CORS headers

- modules/mod_ginger_base/templates/email_base.tpl
Adding an alt text lowers the spam score.
> mod_ginger_base: add alt text to logo in email_base.tpl

- modules/mod_ginger_adlib_elasticsearch2/LICENSE
- modules/mod_ginger_adlib_elasticsearch2/README.md
- modules/mod_ginger_adlib_elasticsearch2/mod_ginger_adlib_elasticsearch2.erl
- modules/mod_ginger_adlib_elasticsearch2/support/ginger_adlib_elasticsearch2_index_mapping.erl
- modules/mod_ginger_adlib_elasticsearch2/support/ginger_adlib_elasticsearch2_mapper.erl
- modules/mod_ginger_adlib_elasticsearch2/support/ginger_adlib_elasticsearch2_mapping.erl
- modules/mod_ginger_adlib_elasticsearch2/templates/_admin_configure_module.tpl
- modules/mod_ginger_collection/mod_ginger_collection.erl
- modules/mod_ginger_collection/models/m_collection_object.erl
- modules/mod_ginger_collection/models/m_ginger_collection.erl
- modules/mod_ginger_collection/support/collection_search.erl
- modules/mod_ginger_collection/templates/_admin_edit_content.beeldenzoeker_query.tpl
- modules/mod_ginger_collection/templates/collection/prevnext.tpl
- modules/mod_ginger_collection/templates/collection/search-query-wrapper.tpl
This must be used with `mod_elasticsearch2`
> Add mod_elasticsearch2 support for Elasticsearch v7+

- modules/mod_ginger_rdf/models/m_dbpedia.erl
- modules/mod_ginger_rdf/support/dbpedia.erl
The nl.dbpedia.org data misses the thumbnail property.
Fetch the thumbnail from the wikipedia page with the `z_url_metadata` routines.
Also add async update of cached dbpedia data, as there are spurious timeouts on the sparql endpoints.
> OP-120: Fetch the dbpedia thumbnail from Wikipedia if it is missing in nl.dbpedia.org.

- modules/mod_ginger_collection/lib/css/src/blocks/_fancybox.scss
- modules/mod_ginger_collection/lib/js/beeldenzoeker.js
This was causing issues in the Hart Amsterdam collection
> Remove afterShow callback for mod_collection fancybox

- modules/mod_ginger_base/support/ginger_search.erl
This fixes standard search with ginger query arguments
> Respect qargs in search

- modules/mod_ginger_base/lib/js/search-suggestions.js
- modules/mod_ginger_base/templates/search-suggestions/search-form.tpl
For sites that have it open by default
> Make disabling of search bar configurable

- modules/mod_ginger_base/scomps/scomp_ginger_base_ginger_search_hash.erl
For linking to search pages with some filters enabled.
> Add ginger_seach_hash scomp

- modules/mod_ginger_base/templates/list/list.tpl
This needs Zotonic >= 0.73 to work correctly
> mod_ginger_base: fix an issue where the show more button was always shown

- modules/mod_ginger_adlib_elasticsearch2/mod_ginger_adlib_elasticsearch2.erl
- modules/mod_ginger_adlib_elasticsearch2/templates/_admin_status.tpl
- modules/mod_ginger_collection/models/m_collection_object.erl
Handle new return values from elasticsearch2:get_doc
> mod_ginger_adlib_elasticearch2: add adlib delete index button.

- modules/mod_ginger_base/support/ginger_handle_net.erl
The code now adds timeouts, which fixes an issue with imports hanging indefinitely when handle.net gives no response.
Also refactored the code to be simpler.
> Fix an issue with hanging imports when handle.net API gives problems

- modules/mod_ginger_rdf/models/m_rdf_triple.erl
Note: currently based on top of #739
> CVN-141 Add ability to replace html from values

- modules/mod_ginger_rdf/models/m_rdf_triple.erl
Follow-up to #740 that includes the predicate name in the function call to replace the HTML.
Needed for [CVN-155](https://driebit.atlassian.net/browse/CVN-155)
> CVN-155 RDF: Include predicates in HTML replacing

- modules/mod_ginger_foundation/lib/css/src/_base.scss
- modules/mod_ginger_foundation/lib/css/src/_mixins.scss
- modules/mod_ginger_foundation/lib/css/src/blocks/_1page-actions-extends.scss
- modules/mod_ginger_foundation/lib/css/src/layout/_global-nav.scss
- modules/mod_ginger_foundation/lib/css/src/layout/_page-actions.scss
This reverts commit f0fe2f4ac959a7bfc04de74e778dcfca2e76cb9f.
> Revert "OEI-70 ginger foundation (#744)"
